### ISSUE TITLE
Add support for creating client auth certificate

### ISSUE THREAD

**Issue by sgallagher** [sgallagher/sscg#13]
Add the ability to also create a client auth certificate signed by the CA.

See https://src.fedoraproject.org/rpms/freeradius/blob/93f241adb12b713ee1169dcbed64f2d556eaa00b/f/freeradius-bootstrap-create-only.patch for an example of what is needed.

**Comment by sgallagher** [comment]
Some notes: when setting up the service certificate, it needs to have the OID `1.3.6.1.5.5.7.3.1` extension in its extensions. For the new client certificate, it will need the OID `1.3.6.1.5.5.7.3.2`.

**Comment by sgallagher** [comment]
See also https://support.microsoft.com/en-us/help/814394/certificate-requirements-when-you-use-eap-tls-or-peap-with-eap-tls for a good overview.

**Comment by jamescassell** [comment]
Awesome! Thanks for adding this support!

**Comment by sgallagher** [comment]
@jamescassell If you have a place to use this, would you mind giving it a try and letting me know if it all works right? My testing of it was limited.
