### ISSUE TITLE
dhparms handling issues

### ISSUE THREAD

**Issue by notroj** [sgallagher/sscg#66]
Following on to c4861e42fc5cdde4d8aa6bccc806e0f71906f6ac - the two most natural ways to do this properly with `mod_ssl` are:

1. use `--dhparams-file=/dev/null` or similar because we are happy with the OpenSSL builtin dhparams
2. use --dhparams-file=/path/to/localhost.crt because OpenSSL will read and use the dhparams if concatenated onto the end of the certificate file - this is standard behaviour for SSL_use_certificate_file() and similar.

But both of these fail with current:

```
+ sscg --cert-file /etc/pki/tls/certs/localhost.crt --dhparams-file /etc/pki/tls/certs/localhost.crt --cert-key-file /etc/pki/tls/private/localhost.key --ca-file /etc/pki/tls/certs/localhost.crt --lifetime 365 --hostname lunaria.manyfish.co.uk --email root@lunaria.manyfish.co.uk
ERROR: The dhparams file may not include other content.
ERROR: Invalid argument
...
+ sscg --cert-file /etc/pki/tls/certs/localhost.crt --dhparams-file /dev/null --cert-key-file /etc/pki/tls/private/localhost.key --ca-file /etc/pki/tls/certs/localhost.crt --lifetime 365 --hostname lunaria.manyfish.co.uk --email root@lunaria.manyfish.co.uk
Could not write to /dev/null. Check directory permissions.
```

Can we get a way to do (1), suppress dhparams generation at least?

**Comment by sgallagher** [comment]
Both of those requests are entirely valid. I'll see what I can do about this next week.

**Comment by sgallagher** [comment]
I got this fixed today and I'll do a release on Monday of 3.0.3. The fix actually revealed some other bugs in the dhparams space, and enough stuff changed that I think a new point release is warranted.

**Comment by notroj** [comment]
Thanks @sgallagher! Would be great if you can also push that to Fedora.

**Comment by sgallagher** [comment]
- [F36](https://bodhi.fedoraproject.org/updates/FEDORA-2023-5fd5dab49f)
- [F37](https://bodhi.fedoraproject.org/updates/FEDORA-2023-975bf63fbe)
- [F38](https://bodhi.fedoraproject.org/updates/FEDORA-2023-afe93b1c88)
