### ISSUE TITLE
Ask for confirmation or refuse if files already exist

### ISSUE THREAD

**Issue by puiterwijk** [sgallagher/sscg#7]
I just had sscg blow away a ca.crt that I had been using because I tried to get the version information (but used lowercase v rather than uppercase v), and it just overwrote the file.

Also running it without any flags will also remove the files, so it might be a good idea to ask for confirmation or just error out if any of the target files already exist.

**Comment by sgallagher** [comment]
@puiterwijk Yeah, I probably need to default to opening with `O_EXCL` unless we pass a `--overwrite` flag.
